services:
  nextjs:
    image: node:22
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development

  rails:
    image: ruby:3
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "bundle install && rake db:create db:migrate && rails server -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data2:
    driver: local
